// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_NE7F2bqH7pnaLGmG_7Fe1CIP8XqhGME',
    appId: '1:1093433118957:web:7c626b0f59a6b390cd7ce4',
    messagingSenderId: '1093433118957',
    projectId: 'hasseb-abud-el-warth',
    authDomain: 'hasseb-abud-el-warth.firebaseapp.com',
    storageBucket: 'hasseb-abud-el-warth.firebasestorage.app',
    measurementId: 'G-EZ7HF24XJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMYhZE36eEj4kPIPMlGU55zOrI2gm5qdQ',
    appId: '1:1093433118957:android:35d5bedac74e9324cd7ce4',
    messagingSenderId: '1093433118957',
    projectId: 'hasseb-abud-el-warth',
    storageBucket: 'hasseb-abud-el-warth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnB3TScb-IfH2X3Q87hI30U6bjS2aLCnU',
    appId: '1:1093433118957:ios:be57f566c1c8571bcd7ce4',
    messagingSenderId: '1093433118957',
    projectId: 'hasseb-abud-el-warth',
    storageBucket: 'hasseb-abud-el-warth.firebasestorage.app',
    iosBundleId: 'com.example.amrRezkEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnB3TScb-IfH2X3Q87hI30U6bjS2aLCnU',
    appId: '1:1093433118957:ios:be57f566c1c8571bcd7ce4',
    messagingSenderId: '1093433118957',
    projectId: 'hasseb-abud-el-warth',
    storageBucket: 'hasseb-abud-el-warth.firebasestorage.app',
    iosBundleId: 'com.example.amrRezkEducation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_NE7F2bqH7pnaLGmG_7Fe1CIP8XqhGME',
    appId: '1:1093433118957:web:978d5b2c5dfbd4d3cd7ce4',
    messagingSenderId: '1093433118957',
    projectId: 'hasseb-abud-el-warth',
    authDomain: 'hasseb-abud-el-warth.firebaseapp.com',
    storageBucket: 'hasseb-abud-el-warth.firebasestorage.app',
    measurementId: 'G-0MCTKBVH43',
  );
}
